#!/usr/bin/env  python3

"""
Pentagon numbers
Problem 44
Pentagonal numbers are generated by the formula, P n = n (3 n −1)/2. The first ten pentagonal
numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P 4 + P 7 = 22 + 70 = 92 = P 8 . However, their difference, 70 − 22 = 48, is not
pentagonal.
Find the pair of pentagonal numbers, P j and P k , for which their sum and difference are pentagonal
and D = |P k − P j | is minimised; what is the value of D?

"""

def pent(n):
    """
    P n = n (3 n −1)/2
    """
    return int(n * ( 3 * n - 1) / 2)

def main():
    solution = 0
    maxi = 10 ** 4
    pents = []

    for x in range(1, maxi):
        #print(x, pent(x))
        pents.append(pent(x))
        
    pentss = set(pents)

    for p in pents[0:maxi//2]:
        #print(".")
        for q in pents[0:maxi//2]:
            #if p == q:
            if p <= q:
                break

            if not (p + q) in pentss:
                continue

            diff = p - q

            if diff in pentss:
                print("XXXXXXXX,", p , q,  p - q)

    print("Solution = %d" % solution)


if __name__ == '__main__':
    main()
