#!/usr/bin/env python3

"""
Triangular, pentagonal, and hexagonal
Problem 45￼
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

def tri_gen():
    n = 0
    while True:
        n += 1 
        yield n * (n+1)//2

def penta_gen():
    n = 0
    while True:
        n += 1
        yield n * (3 * n - 1) // 2


def hexa_gen():
    n = 0
    while True:
        n += 1
        yield n * (2 * n -1) 
 

def main():
    tri = []
    penta = []
    hexa = []
    
    Tri = tri_gen()
    Penta = penta_gen()
    Hexa = hexa_gen()

    ## we can iterate like this as we knwo tri < penta < hexa
    while True:
        tri.append(Tri.__next__())
        penta.append(Penta.__next__())
        hexa.append(Hexa.__next__())
        #print("%d\t%d\t%d" %(tri[-1], penta[-1], hexa[-1]))

        if tri[-1] in penta and tri[-1] in hexa:
            print(tri[-1]) 
            if tri[-1] > 40755:
                print("solution_45: %d" % tri[-1])
                break

if __name__ == "__main__":
    main()
